'use client';

/**
 * InsightsPanel - Real-time insight display component
 *
 * Displays insights generated by the InsightEngine in a visually appealing
 * code-box style panel. Shows severity-based coloring and category badges.
 */

import { motion, AnimatePresence } from 'framer-motion';
import { BRAND_COLORS } from '@/lib/constants/brand';
import {
  useInsights,
  useIsGeneratingInsights,
  useInsightCounts,
  useRealtimeInsights,
} from '@/lib/store';
import type { Insight, InsightSeverity, InsightCategory } from '@/lib/insights/types';
import type { RealtimeInsight } from '@/lib/insights/realtimeInsights';
import {
  AlertCircle,
  AlertTriangle,
  CheckCircle,
  Info,
  Sparkles,
  School,
  Users,
  Clock,
  BookOpen,
  Heart,
  Brain,
  Building,
  Lightbulb,
  Target,
  Award,
  Microscope,
  TrendingUp,
  Zap,
  type LucideIcon,
} from 'lucide-react';

// ============================================================================
// STYLING CONSTANTS
// ============================================================================

const SEVERITY_COLORS: Record<InsightSeverity, { bg: string; border: string; text: string; icon: string }> = {
  critical: {
    bg: 'rgba(220, 38, 38, 0.08)',
    border: 'rgba(220, 38, 38, 0.3)',
    text: '#dc2626',
    icon: '#dc2626',
  },
  warning: {
    bg: 'rgba(217, 119, 6, 0.08)',
    border: 'rgba(217, 119, 6, 0.3)',
    text: '#d97706',
    icon: '#d97706',
  },
  positive: {
    bg: 'rgba(22, 163, 74, 0.08)',
    border: 'rgba(22, 163, 74, 0.3)',
    text: '#16a34a',
    icon: '#16a34a',
  },
  neutral: {
    bg: 'rgba(59, 130, 246, 0.08)',
    border: 'rgba(59, 130, 246, 0.3)',
    text: '#3b82f6',
    icon: '#3b82f6',
  },
};

const CATEGORY_ICONS: Record<InsightCategory, typeof AlertCircle> = {
  HYPER_LOCAL: School,
  CONTEXT: Users,
  TEMPORAL: Clock,
  APTITUDE: BookOpen,
  PASSION: Heart,
  PSYCHOMETRIC: Brain,
  INSTITUTIONAL: Building,
};

const CATEGORY_LABELS: Record<InsightCategory, string> = {
  HYPER_LOCAL: 'Peer Benchmark',
  CONTEXT: 'Context',
  TEMPORAL: 'Timing',
  APTITUDE: 'Academics',
  PASSION: 'Passion',
  PSYCHOMETRIC: 'Psychometric',
  INSTITUTIONAL: 'School Fit',
};

// ============================================================================
// SUB-COMPONENTS
// ============================================================================

function SeverityIcon({ severity }: { severity: InsightSeverity }) {
  const color = SEVERITY_COLORS[severity].icon;
  const iconProps = { className: 'w-4 h-4', style: { color } };

  switch (severity) {
    case 'critical':
      return <AlertCircle {...iconProps} />;
    case 'warning':
      return <AlertTriangle {...iconProps} />;
    case 'positive':
      return <CheckCircle {...iconProps} />;
    case 'neutral':
      return <Info {...iconProps} />;
  }
}

function CategoryBadge({ category }: { category: InsightCategory }) {
  const Icon = CATEGORY_ICONS[category];
  const label = CATEGORY_LABELS[category];

  return (
    <span
      className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium"
      style={{
        backgroundColor: BRAND_COLORS.primaryBg,
        color: BRAND_COLORS.textSecondary,
      }}
    >
      <Icon className="w-3 h-3" />
      {label}
    </span>
  );
}

function InsightCard({ insight }: { insight: Insight }) {
  const colors = SEVERITY_COLORS[insight.severity];

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -10 }}
      className="p-4 rounded-xl"
      style={{
        backgroundColor: colors.bg,
        border: `1px solid ${colors.border}`,
      }}
    >
      <div className="flex items-start gap-3">
        <div className="mt-0.5">
          <SeverityIcon severity={insight.severity} />
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1 flex-wrap">
            <h4
              className="font-semibold text-sm"
              style={{ color: BRAND_COLORS.textHeading }}
            >
              {insight.title}
            </h4>
            <CategoryBadge category={insight.category} />
          </div>
          <p
            className="text-sm leading-relaxed"
            style={{ color: BRAND_COLORS.textPrimary }}
          >
            {insight.message}
          </p>
          {insight.delta && (
            <p
              className="text-xs font-medium mt-2"
              style={{ color: colors.text }}
            >
              {insight.delta}
            </p>
          )}
        </div>
      </div>
    </motion.div>
  );
}

// Real-time insight colors
const REALTIME_COLORS: Record<RealtimeInsight['category'], { bg: string; border: string; text: string; iconBg: string }> = {
  positive: {
    bg: 'rgba(22, 163, 74, 0.08)',
    border: 'rgba(22, 163, 74, 0.3)',
    text: '#16a34a',
    iconBg: 'linear-gradient(135deg, #1DBF73, #15D77C)',
  },
  warning: {
    bg: 'rgba(217, 119, 6, 0.08)',
    border: 'rgba(217, 119, 6, 0.3)',
    text: '#d97706',
    iconBg: 'linear-gradient(135deg, #FFBB00, #EAB705)',
  },
  tip: {
    bg: 'rgba(147, 51, 234, 0.08)',
    border: 'rgba(147, 51, 234, 0.3)',
    text: '#9333ea',
    iconBg: 'linear-gradient(135deg, #7B61FF, #9B7FFF)',
  },
  info: {
    bg: 'rgba(59, 130, 246, 0.08)',
    border: 'rgba(59, 130, 246, 0.3)',
    text: '#3b82f6',
    iconBg: 'linear-gradient(135deg, #55AAAA, #CCE6E6)',
  },
};

// Map category to default icon
const REALTIME_CATEGORY_ICONS: Record<RealtimeInsight['category'], LucideIcon> = {
  positive: CheckCircle,
  warning: AlertTriangle,
  tip: Lightbulb,
  info: Info,
};

// Get appropriate icon based on insight title keywords and category
function getRealtimeInsightIcon(title: string, category: RealtimeInsight['category']): LucideIcon {
  const titleLower = title.toLowerCase();

  if (titleLower.includes('gpa') || titleLower.includes('academic')) return BookOpen;
  if (titleLower.includes('sat') || titleLower.includes('act') || titleLower.includes('test')) return Target;
  if (titleLower.includes('leadership')) return Award;
  if (titleLower.includes('research') || titleLower.includes('publication')) return Microscope;
  if (titleLower.includes('service') || titleLower.includes('community')) return Heart;
  if (titleLower.includes('rigor') || titleLower.includes('ap') || titleLower.includes('course') || titleLower.includes('ib')) return TrendingUp;
  if (titleLower.includes('impact') || titleLower.includes('reach')) return Users;
  if (titleLower.includes('first-gen') || titleLower.includes('first gen') || titleLower.includes('pioneer')) return Zap;

  return REALTIME_CATEGORY_ICONS[category];
}

function RealtimeInsightCard({ insight, isLatest }: { insight: RealtimeInsight; isLatest: boolean }) {
  const colors = REALTIME_COLORS[insight.category];
  const timeAgo = getTimeAgo(insight.timestamp);
  const IconComponent = getRealtimeInsightIcon(insight.title, insight.category);

  return (
    <motion.div
      initial={{ opacity: 0, y: -10, scale: 0.95 }}
      animate={{ opacity: 1, y: 0, scale: 1 }}
      exit={{ opacity: 0, scale: 0.95 }}
      transition={{ duration: 0.3 }}
      className="p-4 rounded-xl"
      style={{
        backgroundColor: colors.bg,
        border: `1px solid ${colors.border}`,
        boxShadow: isLatest ? `0 0 0 2px ${BRAND_COLORS.primary}40` : undefined,
      }}
    >
      <div className="flex items-start gap-3">
        {/* Lucide icon in gradient circle */}
        <div
          className="flex-shrink-0 w-10 h-10 rounded-full flex items-center justify-center"
          style={{
            background: colors.iconBg,
            boxShadow: `0 4px 12px ${colors.text}40`,
          }}
        >
          <IconComponent className="w-5 h-5 text-white" strokeWidth={2.5} />
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1 flex-wrap">
            <h4
              className="font-semibold text-sm"
              style={{ color: BRAND_COLORS.textHeading }}
            >
              {insight.title}
            </h4>
            {isLatest && (
              <span
                className="text-xs font-medium px-2 py-0.5 rounded-full"
                style={{
                  backgroundColor: BRAND_COLORS.primary,
                  color: 'white',
                }}
              >
                NEW
              </span>
            )}
          </div>
          <p
            className="text-sm leading-relaxed"
            style={{ color: BRAND_COLORS.textPrimary }}
          >
            {insight.message}
          </p>
          <p
            className="text-xs mt-2"
            style={{ color: BRAND_COLORS.textMuted }}
          >
            {timeAgo}
          </p>
        </div>
      </div>
    </motion.div>
  );
}

function getTimeAgo(timestamp: number): string {
  const seconds = Math.floor((Date.now() - timestamp) / 1000);
  if (seconds < 5) return 'Just now';
  if (seconds < 60) return `${seconds}s ago`;
  if (seconds < 3600) return `${Math.floor(seconds / 60)}m ago`;
  if (seconds < 86400) return `${Math.floor(seconds / 3600)}h ago`;
  return `${Math.floor(seconds / 86400)}d ago`;
}

function InsightsSummary() {
  const counts = useInsightCounts();

  const items = [
    { label: 'Critical', count: counts.critical, color: SEVERITY_COLORS.critical.text },
    { label: 'Warning', count: counts.warning, color: SEVERITY_COLORS.warning.text },
    { label: 'Positive', count: counts.positive, color: SEVERITY_COLORS.positive.text },
    { label: 'Info', count: counts.neutral, color: SEVERITY_COLORS.neutral.text },
  ].filter((item) => item.count > 0);

  if (items.length === 0) return null;

  return (
    <div className="flex flex-wrap gap-3 mb-4">
      {items.map((item) => (
        <span
          key={item.label}
          className="inline-flex items-center gap-1.5 text-xs font-medium"
        >
          <span
            className="w-2 h-2 rounded-full"
            style={{ backgroundColor: item.color }}
          />
          <span style={{ color: BRAND_COLORS.textSecondary }}>
            {item.count} {item.label}
          </span>
        </span>
      ))}
    </div>
  );
}

// ============================================================================
// MAIN COMPONENT
// ============================================================================

interface InsightsPanelProps {
  /** Maximum number of insights to display (default: 5) */
  maxInsights?: number;
  /** Show only specific severities */
  severities?: InsightSeverity[];
  /** Show only specific categories */
  categories?: InsightCategory[];
  /** Show the summary bar (default: true) */
  showSummary?: boolean;
  /** Custom title (default: "Real-time Insights") */
  title?: string;
  /** Additional CSS classes */
  className?: string;
}

export function InsightsPanel({
  maxInsights = 5,
  severities,
  categories,
  showSummary = true,
  title = 'Profile Insights',
  className = '',
}: InsightsPanelProps) {
  const allInsights = useInsights();
  const realtimeInsights = useRealtimeInsights();
  const isGenerating = useIsGeneratingInsights();

  // Filter insights based on props
  let filteredInsights = allInsights;

  if (severities && severities.length > 0) {
    filteredInsights = filteredInsights.filter((i) => severities.includes(i.severity));
  }

  if (categories && categories.length > 0) {
    filteredInsights = filteredInsights.filter((i) => categories.includes(i.category));
  }

  // Sort by priority (highest first) and take top N
  const displayInsights = [...filteredInsights]
    .sort((a, b) => b.priority - a.priority)
    .slice(0, maxInsights);

  // Sort realtime insights by timestamp (newest first) and take top 5
  const displayRealtimeInsights = [...realtimeInsights]
    .sort((a, b) => b.timestamp - a.timestamp)
    .slice(0, 5);

  const hasAnyInsights = displayInsights.length > 0 || displayRealtimeInsights.length > 0;

  return (
    <div
      className={`rounded-xl ${className}`}
      style={{
        backgroundColor: BRAND_COLORS.primaryBg,
        border: `2px solid ${BRAND_COLORS.primary}20`,
        padding: '20px',
      }}
    >
      {/* Header */}
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <Sparkles className="w-5 h-5" style={{ color: BRAND_COLORS.primary }} />
          <h3
            className="font-semibold"
            style={{ color: BRAND_COLORS.textHeading }}
          >
            {title}
          </h3>
        </div>
        {isGenerating && (
          <div className="flex items-center gap-2">
            <div
              className="w-3 h-3 rounded-full animate-pulse"
              style={{ backgroundColor: BRAND_COLORS.primary }}
            />
            <span
              className="text-xs"
              style={{ color: BRAND_COLORS.textMuted }}
            >
              Analyzing...
            </span>
          </div>
        )}
      </div>

      {/* Summary */}
      {showSummary && <InsightsSummary />}

      {/* Insights List */}
      <div className="space-y-3 max-h-[500px] overflow-y-auto">
        <AnimatePresence mode="popLayout">
          {/* Real-time insights first (newest) */}
          {displayRealtimeInsights.map((insight, index) => (
            <RealtimeInsightCard
              key={insight.id}
              insight={insight}
              isLatest={index === 0}
            />
          ))}

          {/* Original insights from InsightEngine */}
          {displayInsights.map((insight) => (
            <InsightCard key={insight.id} insight={insight} />
          ))}

          {/* Empty state */}
          {!hasAnyInsights && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="text-center py-8"
            >
              <div
                className="w-12 h-12 rounded-full mx-auto mb-3 flex items-center justify-center"
                style={{ backgroundColor: BRAND_COLORS.bgPrimary }}
              >
                <Sparkles className="w-6 h-6" style={{ color: BRAND_COLORS.textMuted }} />
              </div>
              <p
                className="text-sm"
                style={{ color: BRAND_COLORS.textMuted }}
              >
                Complete your profile to see personalized insights
              </p>
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* Show more indicator */}
      {filteredInsights.length > maxInsights && (
        <p
          className="text-xs text-center mt-4"
          style={{ color: BRAND_COLORS.textMuted }}
        >
          +{filteredInsights.length - maxInsights} more insights available
        </p>
      )}
    </div>
  );
}

export default InsightsPanel;
