'use client';

/**
 * InsightsPanel - Real-time insight display component
 *
 * Displays insights generated by the InsightEngine in a visually appealing
 * code-box style panel. Shows severity-based coloring and category badges.
 */

import { motion, AnimatePresence } from 'framer-motion';
import { BRAND_COLORS } from '@/lib/constants/brand';
import {
  useInsights,
  useIsGeneratingInsights,
  useInsightCounts,
} from '@/lib/store';
import type { Insight, InsightSeverity, InsightCategory } from '@/lib/insights/types';
import {
  AlertCircle,
  AlertTriangle,
  CheckCircle,
  Info,
  Sparkles,
  School,
  Users,
  Clock,
  BookOpen,
  Heart,
  Brain,
  Building,
} from 'lucide-react';

// ============================================================================
// STYLING CONSTANTS
// ============================================================================

const SEVERITY_COLORS: Record<InsightSeverity, { bg: string; border: string; text: string; icon: string }> = {
  critical: {
    bg: 'rgba(220, 38, 38, 0.08)',
    border: 'rgba(220, 38, 38, 0.3)',
    text: '#dc2626',
    icon: '#dc2626',
  },
  warning: {
    bg: 'rgba(217, 119, 6, 0.08)',
    border: 'rgba(217, 119, 6, 0.3)',
    text: '#d97706',
    icon: '#d97706',
  },
  positive: {
    bg: 'rgba(22, 163, 74, 0.08)',
    border: 'rgba(22, 163, 74, 0.3)',
    text: '#16a34a',
    icon: '#16a34a',
  },
  neutral: {
    bg: 'rgba(59, 130, 246, 0.08)',
    border: 'rgba(59, 130, 246, 0.3)',
    text: '#3b82f6',
    icon: '#3b82f6',
  },
};

const CATEGORY_ICONS: Record<InsightCategory, typeof AlertCircle> = {
  HYPER_LOCAL: School,
  CONTEXT: Users,
  TEMPORAL: Clock,
  APTITUDE: BookOpen,
  PASSION: Heart,
  PSYCHOMETRIC: Brain,
  INSTITUTIONAL: Building,
};

const CATEGORY_LABELS: Record<InsightCategory, string> = {
  HYPER_LOCAL: 'Peer Benchmark',
  CONTEXT: 'Context',
  TEMPORAL: 'Timing',
  APTITUDE: 'Academics',
  PASSION: 'Passion',
  PSYCHOMETRIC: 'Psychometric',
  INSTITUTIONAL: 'School Fit',
};

// ============================================================================
// SUB-COMPONENTS
// ============================================================================

function SeverityIcon({ severity }: { severity: InsightSeverity }) {
  const color = SEVERITY_COLORS[severity].icon;
  const iconProps = { className: 'w-4 h-4', style: { color } };

  switch (severity) {
    case 'critical':
      return <AlertCircle {...iconProps} />;
    case 'warning':
      return <AlertTriangle {...iconProps} />;
    case 'positive':
      return <CheckCircle {...iconProps} />;
    case 'neutral':
      return <Info {...iconProps} />;
  }
}

function CategoryBadge({ category }: { category: InsightCategory }) {
  const Icon = CATEGORY_ICONS[category];
  const label = CATEGORY_LABELS[category];

  return (
    <span
      className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-xs font-medium"
      style={{
        backgroundColor: BRAND_COLORS.primaryBg,
        color: BRAND_COLORS.textSecondary,
      }}
    >
      <Icon className="w-3 h-3" />
      {label}
    </span>
  );
}

function InsightCard({ insight }: { insight: Insight }) {
  const colors = SEVERITY_COLORS[insight.severity];

  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -10 }}
      className="p-4 rounded-xl"
      style={{
        backgroundColor: colors.bg,
        border: `1px solid ${colors.border}`,
      }}
    >
      <div className="flex items-start gap-3">
        <div className="mt-0.5">
          <SeverityIcon severity={insight.severity} />
        </div>
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2 mb-1 flex-wrap">
            <h4
              className="font-semibold text-sm"
              style={{ color: BRAND_COLORS.textHeading }}
            >
              {insight.title}
            </h4>
            <CategoryBadge category={insight.category} />
          </div>
          <p
            className="text-sm leading-relaxed"
            style={{ color: BRAND_COLORS.textPrimary }}
          >
            {insight.message}
          </p>
          {insight.delta && (
            <p
              className="text-xs font-medium mt-2"
              style={{ color: colors.text }}
            >
              {insight.delta}
            </p>
          )}
        </div>
      </div>
    </motion.div>
  );
}

function InsightsSummary() {
  const counts = useInsightCounts();

  const items = [
    { label: 'Critical', count: counts.critical, color: SEVERITY_COLORS.critical.text },
    { label: 'Warning', count: counts.warning, color: SEVERITY_COLORS.warning.text },
    { label: 'Positive', count: counts.positive, color: SEVERITY_COLORS.positive.text },
    { label: 'Info', count: counts.neutral, color: SEVERITY_COLORS.neutral.text },
  ].filter((item) => item.count > 0);

  if (items.length === 0) return null;

  return (
    <div className="flex flex-wrap gap-3 mb-4">
      {items.map((item) => (
        <span
          key={item.label}
          className="inline-flex items-center gap-1.5 text-xs font-medium"
        >
          <span
            className="w-2 h-2 rounded-full"
            style={{ backgroundColor: item.color }}
          />
          <span style={{ color: BRAND_COLORS.textSecondary }}>
            {item.count} {item.label}
          </span>
        </span>
      ))}
    </div>
  );
}

// ============================================================================
// MAIN COMPONENT
// ============================================================================

interface InsightsPanelProps {
  /** Maximum number of insights to display (default: 5) */
  maxInsights?: number;
  /** Show only specific severities */
  severities?: InsightSeverity[];
  /** Show only specific categories */
  categories?: InsightCategory[];
  /** Show the summary bar (default: true) */
  showSummary?: boolean;
  /** Custom title (default: "Real-time Insights") */
  title?: string;
  /** Additional CSS classes */
  className?: string;
}

export function InsightsPanel({
  maxInsights = 5,
  severities,
  categories,
  showSummary = true,
  title = 'Real-time Insights',
  className = '',
}: InsightsPanelProps) {
  const allInsights = useInsights();
  const isGenerating = useIsGeneratingInsights();

  // Filter insights based on props
  let filteredInsights = allInsights;

  if (severities && severities.length > 0) {
    filteredInsights = filteredInsights.filter((i) => severities.includes(i.severity));
  }

  if (categories && categories.length > 0) {
    filteredInsights = filteredInsights.filter((i) => categories.includes(i.category));
  }

  // Sort by priority (highest first) and take top N
  const displayInsights = [...filteredInsights]
    .sort((a, b) => b.priority - a.priority)
    .slice(0, maxInsights);

  return (
    <div
      className={`rounded-xl ${className}`}
      style={{
        backgroundColor: BRAND_COLORS.primaryBg,
        border: `2px solid ${BRAND_COLORS.primary}20`,
        padding: '20px',
      }}
    >
      {/* Header */}
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <Sparkles className="w-5 h-5" style={{ color: BRAND_COLORS.primary }} />
          <h3
            className="font-semibold"
            style={{ color: BRAND_COLORS.textHeading }}
          >
            {title}
          </h3>
        </div>
        {isGenerating && (
          <div className="flex items-center gap-2">
            <div
              className="w-3 h-3 rounded-full animate-pulse"
              style={{ backgroundColor: BRAND_COLORS.primary }}
            />
            <span
              className="text-xs"
              style={{ color: BRAND_COLORS.textMuted }}
            >
              Analyzing...
            </span>
          </div>
        )}
      </div>

      {/* Summary */}
      {showSummary && <InsightsSummary />}

      {/* Insights List */}
      <div className="space-y-3">
        <AnimatePresence mode="popLayout">
          {displayInsights.length > 0 ? (
            displayInsights.map((insight) => (
              <InsightCard key={insight.id} insight={insight} />
            ))
          ) : (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              className="text-center py-8"
            >
              <div
                className="w-12 h-12 rounded-full mx-auto mb-3 flex items-center justify-center"
                style={{ backgroundColor: BRAND_COLORS.bgPrimary }}
              >
                <Sparkles className="w-6 h-6" style={{ color: BRAND_COLORS.textMuted }} />
              </div>
              <p
                className="text-sm"
                style={{ color: BRAND_COLORS.textMuted }}
              >
                Complete your profile to see personalized insights
              </p>
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* Show more indicator */}
      {filteredInsights.length > maxInsights && (
        <p
          className="text-xs text-center mt-4"
          style={{ color: BRAND_COLORS.textMuted }}
        >
          +{filteredInsights.length - maxInsights} more insights available
        </p>
      )}
    </div>
  );
}

export default InsightsPanel;
