export const BRAND_COLORS = {
  primary: '#641432',
  primaryLight: '#8B1E4A',
  primaryBg: '#FFF5F2',
  accent: '#FF4A23',
  accentLight: '#FF6B47',
  accentBg: '#FFF7ED',
  textHeading: '#1F2937',
  textPrimary: '#374151',
  textSecondary: '#6B7280',
  textMuted: '#9CA3AF',
  bgPrimary: '#FFFFFF',
  bgSecondary: '#F9FAFB',
  borderLight: '#E5E7EB',
  success: '#059669',
  successBg: '#D1FAE5',
  warning: '#D97706',
  warningBg: '#FEF3C7',
  error: '#DC2626',
  errorBg: '#FEE2E2',
  info: '#2563EB',
  infoBg: '#DBEAFE',
  aptitude: '#2563EB',
  passion: '#F97316',
  service: '#059669',
  identity: '#7C3AED',
  edge: '#D97706',
  edgeBg: '#FEF3C7',
} as const;

export const CATEGORY_CONFIG = {
  aptitude: { label: 'Aptitude', color: BRAND_COLORS.aptitude, bgColor: BRAND_COLORS.infoBg },
  passion: { label: 'Passion', color: BRAND_COLORS.passion, bgColor: BRAND_COLORS.accentBg },
  service: { label: 'Service', color: BRAND_COLORS.service, bgColor: BRAND_COLORS.successBg },
  identity: { label: 'Identity', color: BRAND_COLORS.identity, bgColor: '#EDE9FE' },
} as const;
